import { randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { PrismaClient } from '@prisma/client';
import dotenv from 'dotenv';
import express from 'express';
import jwt from 'jsonwebtoken';
import passport from 'passport';
import request from 'supertest';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { commandBus } from '../src/application/command-bus.js';
import { ArchiveRecipeCommandHandler } from '../src/application/handlers/ArchiveRecipeCommandHandler.js';
import {
  GetRecipesQueryHandler, SearchRecipesQueryHandler, GetManageableRecipesQueryHandler, GetRecipeBySlugQueryHandler,
} from '../src/application/handlers/RecipeQueryHandlers.js';
import { RecipeRepository } from '../src/infrastructure/persistence/repositories/RecipeRepository.js';
import { globalErrorHandler } from '../src/presentation/middleware/GlobalErrorHandler.js';
import recipeRoutes from '../src/presentation/routes/recipeRoutes.js';
import { cacheService } from '../src/infrastructure/cache/RedisCacheService.js';

// Explicit opt-in: this suite writes isolated fixtures to the configured database and removes them.
describe.skipIf(process.env.RUN_RECIPE_ARCHIVE_E2E !== '1')('Archive Recipe with real PostgreSQL and JWT strategy', () => {
  let prisma: PrismaClient;
  let app: express.Express;
  const owner = randomUUID();
  const other = randomUUID();
  const admin = randomUUID();
  const categoryId = randomUUID();
  const recipeId = randomUUID();
  const slug = `archive-e2e-${recipeId}`;
  const bearer = (userId: string) => jwt.sign({ userId }, process.env.JWT_ACCESS_SECRET!, { expiresIn: 300 });

  beforeAll(async () => {
    // Read only DATABASE_URL; never print credentials or change the project's .env.
    try {
      const settings = dotenv.parse(readFileSync('.env'));
      if (settings.DATABASE_URL) process.env.DATABASE_URL = settings.DATABASE_URL;
    } catch { /* CI can supply DATABASE_URL without a .env file. */ }
    prisma = new PrismaClient();
    await prisma.$connect();
    await cacheService.connect();
    const { configureJwtStrategy } = await import('../src/infrastructure/auth/strategies/JwtStrategy.js');
    configureJwtStrategy(passport);
    await prisma.user.createMany({ data: [
      { id: owner, email: `archive-owner-${owner}@example.test`, displayName: 'Archive E2E owner', role: 'AUTHOR' },
      { id: other, email: `archive-other-${other}@example.test`, displayName: 'Archive E2E other', role: 'AUTHOR' },
      { id: admin, email: `archive-admin-${admin}@example.test`, displayName: 'Archive E2E admin', role: 'ADMIN' },
    ] });
    await prisma.category.create({ data: { id: categoryId, name: slug, slug } });
    await prisma.recipe.create({ data: {
      id: recipeId, title: 'Archive E2E recipe', slug, description: 'Isolated archive integration fixture',
      categoryId, authorId: owner, prepTime: 10, cookTime: 20, servings: 2, status: 'PUBLISHED',
      publishedAt: new Date(),
      steps: { create: { stepNumber: 1, title: 'Cook', description: 'Cook all ingredients' } },
      ingredients: { create: { name: 'Beef', quantity: 1, orderIndex: 0 } },
      images: { create: { originalUrl: 'https://example.test/recipe.png', isPrimary: true } },
    } });
    const repository = new RecipeRepository(prisma);
    commandBus.registerCommandHandler('ArchiveRecipeCommand', new ArchiveRecipeCommandHandler(prisma));
    commandBus.registerQueryHandler('GetRecipesQuery', new GetRecipesQueryHandler(repository));
    commandBus.registerQueryHandler('SearchRecipesQuery', new SearchRecipesQueryHandler(repository));
    commandBus.registerQueryHandler('GetManageableRecipesQuery', new GetManageableRecipesQueryHandler(repository));
    commandBus.registerQueryHandler('GetRecipeBySlugQuery', new GetRecipeBySlugQueryHandler(prisma));
    app = express();
    app.use(express.json(), passport.initialize());
    app.use('/api/v1/recipes', recipeRoutes);
    app.use(globalErrorHandler);
  }, 30000);

  afterAll(async () => {
    if (!prisma) return;
    try {
      // These IDs were generated by this suite; existing project records are never cleanup targets.
      await prisma.recipe.deleteMany({ where: { id: recipeId } });
      await prisma.category.deleteMany({ where: { id: categoryId } });
      await prisma.user.deleteMany({ where: { id: { in: [owner, other, admin] } } });
    } finally {
      await cacheService.disconnect();
      await prisma.$disconnect();
    }
  }, 30000);

  it('archives through HTTP, persists status, preserves relations, hides public results, and allows owner/Admin access', async () => {
    const publicBefore = await request(app).get(`/api/v1/recipes?categoryId=${categoryId}`);
    expect(publicBefore.status).toBe(200);
    expect(publicBefore.body.items.map((item: { id: string }) => item.id)).toContain(recipeId);
    expect((await request(app).patch(`/api/v1/recipes/${recipeId}/archive`)).status).toBe(401);
    expect((await request(app).patch(`/api/v1/recipes/${recipeId}/archive`)
      .auth(bearer(other), { type: 'bearer' })).status).toBe(403);
    const listCacheKey = `recipes:archive-e2e:${recipeId}`;
    const detailCacheKey = `recipe:${recipeId}`;
    await cacheService.set(listCacheKey, { items: [{ id: recipeId }] }, 300);
    await cacheService.set(detailCacheKey, { id: recipeId, status: 'PUBLISHED' }, 300);
    expect(await cacheService.exists(listCacheKey)).toBe(true);
    const response = await request(app).patch(`/api/v1/recipes/${recipeId}/archive`)
      .auth(bearer(owner), { type: 'bearer' });
    expect(response.status).toBe(200);
    expect(response.body).toMatchObject({ id: recipeId, status: 'ARCHIVED' });
    expect(await cacheService.exists(listCacheKey)).toBe(false);
    expect(await cacheService.exists(detailCacheKey)).toBe(false);
    const stored = await prisma.recipe.findUniqueOrThrow({
      where: { id: recipeId }, include: { steps: true, ingredients: true, images: true },
    });
    expect(stored.status).toBe('ARCHIVED');
    expect(stored.isDeleted).toBe(false);
    expect(stored.steps).toHaveLength(1);
    expect(stored.ingredients).toHaveLength(1);
    expect(stored.images).toHaveLength(1);
    expect(stored.publishedAt).not.toBeNull();
    for (const path of [
      `/api/v1/recipes?categoryId=${categoryId}`,
      `/api/v1/recipes/search?q=Archive&categoryId=${categoryId}&status=ARCHIVED`,
    ]) {
      const result = await request(app).get(path);
      expect(result.status).toBe(200);
      expect(result.body.items).toEqual([]);
      expect(result.body.meta.totalCount).toBe(0);
    }
    expect((await request(app).get(`/api/v1/recipes/${slug}`)).status).toBe(404);
    for (const user of [owner, admin]) {
      const manageable = await request(app).get(`/api/v1/recipes/manageable?categoryId=${categoryId}&status=ARCHIVED`)
        .auth(bearer(user), { type: 'bearer' });
      expect(manageable.status).toBe(200);
      expect(manageable.body.items[0].id).toBe(recipeId);
      expect((await request(app).get(`/api/v1/recipes/${slug}`)
        .auth(bearer(user), { type: 'bearer' })).status).toBe(200);
    }
    // Admin may archive another author's recipe.
    await prisma.recipe.update({ where: { id: recipeId }, data: { status: 'PUBLISHED' } });
    expect((await request(app).patch(`/api/v1/recipes/${recipeId}/archive`)
      .auth(bearer(admin), { type: 'bearer' })).status).toBe(200);
    const version = (await prisma.recipe.findUniqueOrThrow({ where: { id: recipeId } })).version;
    expect((await request(app).patch(`/api/v1/recipes/${recipeId}/archive`)
      .auth(bearer(owner), { type: 'bearer' })).status).toBe(200);
    expect((await prisma.recipe.findUniqueOrThrow({ where: { id: recipeId } })).version).toBe(version);
  }, 30000);
});
